# Generated by Django 4.2.5 on 2025-07-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0002_internshipcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeschallan',
            name='clg',
            field=models.CharField(max_length=200),
        ),
    ]
