# Generated by Django 4.2.5 on 2025-07-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0003_alter_feeschallan_clg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
