# Generated by Django 4.2.5 on 2025-07-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0005_alter_contactmessage_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchallotment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
