# Generated by Django 4.2.5 on 2025-07-13 21:09

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0006_alter_batchallotment_photo'),
    ]

    operations = [
         migrations.AlterField(
            model_name='studentlogin',
            name='rollno',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
    

    operations = [
        migrations.AddField(
            model_name='studentlogin',
            name='email',
            field=models.EmailField(max_length=254, default='dummy@example.com'),
            preserve_default=False,
        ),
    ]

