# Generated by Django 4.2.5 on 2025-07-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0007_auto_20250714_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
