# Generated by Django 4.2.5 on 2025-07-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0008_alter_reg_email_alter_studentlogin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchallotment',
            name='project',
            field=models.CharField(max_length=250),
        ),
    ]
