# Generated by Django 4.2.5 on 2025-07-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0009_alter_batchallotment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlogin',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
