# Generated by Django 4.2.5 on 2025-07-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0010_studentlogin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogin',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
