# Generated by Django 4.2.5 on 2025-07-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0011_alter_studentlogin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchallotment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
