# Generated by Django 4.2.5 on 2025-07-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0012_alter_batchallotment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchallotment',
            old_name='uniqueId',
            new_name='uid',
        ),
    ]
