# Generated by Django 4.2.5 on 2025-07-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0014_challan'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchallotment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
