# Generated by Django 4.2.5 on 2025-07-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0015_batchallotment_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=200)),
                ('duration_from', models.DateField()),
                ('duration_to', models.DateField()),
                ('project_name_1', models.TextField()),
                ('project_name_2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InternshipCertificate',
        ),
    ]
