# Generated by Django 4.2.5 on 2025-07-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0016_certificate_delete_internshipcertificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.AddField(
            model_name='batchallotment',
            name='certificate_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
