# Generated by Django 4.2.5 on 2025-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0017_delete_certificate_batchallotment_certificate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchallotment',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
