# Generated by Django 4.2.5 on 2025-07-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0018_alter_batchallotment_certificate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.IntegerField()),
            ],
        ),
    ]
