# Generated by Django 4.2.5 on 2025-07-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0019_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='stvt.reg'),
        ),
    ]
