# Generated by Django 4.2.5 on 2025-07-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0021_alter_certificate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='branch',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='batchallotment',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='feeschallan',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reg',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
