# Generated by Django 4.2.5 on 2025-07-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0022_reg_branch_alter_batchallotment_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='branch',
            field=models.CharField(max_length=100),
        ),
    ]
