# Generated by Django 4.2.5 on 2025-07-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0023_alter_reg_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='branch',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
