# Generated by Django 4.2.5 on 2025-07-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0024_alter_reg_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchallotment',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='feeschallan',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lorsubmission',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reg',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
