# Generated by Django 4.2.5 on 2025-07-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0025_alter_batchallotment_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchallotment',
            name='certificate_number',
        ),
        migrations.AddField(
            model_name='batchallotment',
            name='report_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchallotment',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feeschallan',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lorsubmission',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reg',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
