# Generated by Django 4.2.5 on 2025-07-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0026_remove_batchallotment_certificate_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=20)),
            ],
        ),
    ]
