# Generated by Django 4.2.5 on 2025-07-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0027_trainingstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingStudent',
        ),
    ]
