# Generated by Django 4.2.5 on 2025-07-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0028_delete_trainingstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchallotment',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
