# Generated by Django 4.2.5 on 2025-07-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0029_alter_batchallotment_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchallotment',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
