# Generated by Django 4.2.5 on 2025-07-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0031_alter_batchallotment_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchallotment',
            name='report_name',
        ),
        migrations.AddField(
            model_name='batchallotment',
            name='project_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='batchallotment',
            name='report_to',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
