# Generated by Django 4.2.5 on 2025-07-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvt', '0032_remove_batchallotment_report_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchallotment',
            name='batch_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
